services:
  postgres:
    container_name: identity-server-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: dbu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: identity
    ports:
      - '5432:5432'
    networks:
      - dev

  redis:
    container_name: identity-server-redis
    image: redis:latest
    restart: on-failure
    ports:
      - '6379:6379'
    networks:
      - dev

  application:
    container_name: identity-server-application
    build: .
    restart: unless-stopped
    ports:
      - '8443:8443'
    depends_on:
      - postgres
      - redis
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge