services:
  debezium:
    container_name: debezium
    image: debezium/connect:3.0.0.Final
    restart: always
    environment:
      BOOTSTRAP_SERVERS: broker-1:19092,broker-2:29092,broker-3:39092
      GROUP_ID: debezium-group
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: /kafka/connect
      CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
    ports:
      - "8083:8083"
    volumes:
      - ./connectors:/kafka/connect
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge