ALTER ROLE dbu WITH REPLICATION;
GRANT CONNECT ON DATABASE "budget-command" TO dbu;

GRANT USAGE ON SCHEMA public TO dbu;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbu;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dbu;